[package]
name = "udev-netlink"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.26.2"
memchr = "2.5.0"
bytemuck = { version = "1.13.1", features = ["derive"] }
memoffset = "0.8"
murmur2 = "0.1.0"